### ISSUE TITLE
Minor: research requires military science bottles, but doesn't have military science as a prerequisite in the tree.

### ISSUE THREAD

**Issue by EchoTangoNonIndustries** [ChurchOrganist/Long_Range_Radar#12]
Before you've researched military science, you can try to research this, but you'll be unable to make progress because you can't make military science bottles yet.

**Comment by DRY411S** [comment]
Fair point. Regrettably, the author of this mod passed away in 2021, and the mod is no longer being maintained.

If you unzip the mod, and edit line 15 of technology.lua from:

`prerequisites = {"military-2", "electronics","railway"},`

to:

`prerequisites = {"military-science-pack", "electronics","railway"},`

then this will make the radar research dependent on military science research.
