### ISSUE TITLE
Enhancement suggestion: Add support for upgrade planner

### ISSUE THREAD

**Issue by DRY411S** [ChurchOrganist/Long_Range_Radar#7]
How about adding the capability in the upgrade planner to let players choose to upgrade to your radar from the vanilla version?

**Comment by ChurchOrganist** [comment]
That is an excellent proposal - I just need to work out how to do it.

As usual the Factorio API is opaque on the topic :(

All I can say is........
Watch this space :)

**Comment by DRY411S** [comment]
https://lua-api.factorio.com/latest/LuaEntityPrototype.html#LuaEntityPrototype.next_upgrade

You will have to add the name of your radar as the next_upgrade on the vanilla radar.

Easy peasy.

**Comment by ChurchOrganist** [comment]
Implemented in version 0.18.03 - 10/07/2020
