### ISSUE TITLE
Wrong icon size in electric network info screen

### ISSUE THREAD

**Issue by SteveS8** [ChurchOrganist/Long_Range_Radar#8]
The icon shown in the power consumption screen seems to be twice the size it should be

**Comment by ChurchOrganist** [comment]
That's weird - no idea what's causing that - will look into it shortly

**Comment by ChurchOrganist** [comment]
OK I've worked out what the problem is - a fix will be out soon

**Comment by ChurchOrganist** [comment]
This is now fixed for the next release. As it's so minor I shall be including it with the fast replace update I'm currently working on.
